export type ReceiveForm = {
  receive_code: string;
  reference_no: string;
  customer_id: string;
  customer_code: string;
  customer_name: string;
  shipper_id: string;
  shipper_code: string;
  shipper_name: string;
  shipper_address: string;
  shipper_subdistrict_id: string;
  shipper_district_id: string;
  shipper_province_id: string;
  shipper_subdistrict_name: string;
  shipper_district_name: string;
  shipper_province_name: string;
  shipper_zip_code: string;
  shipper_tel: string;
  recipient_id: string;
  recipient_code: string;
  recipient_detail_id: string;
  recipient_detail_name: string;
  recipient_name: string;
  address: string;
  province_id: string;
  district_id: string;
  subdistrict_id: string;
  province_name: string;
  district_name: string;
  subdistrict_name: string;
  zip_code: string;
  tel: string;
  delivery_date: string;
  payment_type_id: string;
  remark: string;
  is_cod: "Y" | "N";
  cod: string;
  is_document_return: "Y" | "N";
  document_return: string;
  is_pickup_customer: "Y" | "N";
  is_pickup_shipper: "Y" | "N";
};

export type CustomerOption = { id: number; code: string; name: string };
export type PaymentOption = { id: number; name: string };
export type ShipperOption = {
  shipper_id: number;
  shipper_code: string;
  shipper_name: string;
  address: string;
  tel?: string | null;
  zip_code?: string | null;
  subdistrict_id?: number | null;
  district_id?: number | null;
  province_id?: number | null;
  subdistrict_name?: string | null;
  district_name?: string | null;
  province_name?: string | null;
};
export type RecipientOption = {
  recipient_id: number;
  recipient_code: string;
  recipient_name: string;
  recipient_detail_id?: number | null;
  recipient_detail_name?: string | null;
  address?: string | null;
  tel?: string | null;
  zip_code?: string | null;
  subdistrict_id?: number | null;
  district_id?: number | null;
  province_id?: number | null;
  subdistrict_name?: string | null;
  district_name?: string | null;
  province_name?: string | null;
};
export type GroupedRecipient = { recipient_id: number; recipient: RecipientOption; details: RecipientOption[] };
export type PackageOption = {
  package_id: number | string;
  package_code?: string | null;
  package_name?: string | null;
  customer_id?: number | string | null;
  type?: string | null;
  package_detail_id?: number | string | null;
  package_detail_code?: string | null;
  package_detail_name?: string | null;
  unit_id?: number | string | null;
  size_min?: number | string | null;
  size_max?: number | string | null;
  weight_min?: number | string | null;
  weight_max?: number | string | null;
  cost?: number | string | null;
  cost_difference_warehouse?: number | string | null;
  cost_go?: number | string | null;
  cost_return?: number | string | null;
  is_document_return?: string | null;
  is_weight_fix?: string | null;
  is_vat?: string | null;
  package_detail_type?: "BUSINESS" | "EXPRESS" | string | null;
};
export type GroupedPackageOption = { package_id: string; package_code: string; package_name: string; type: string; details: PackageOption[] };
export type PackageRow = {
  package_id: string;
  package_code: string;
  package_name: string;
  package_detail_id: string;
  package_detail_code: string;
  package_detail_type: string;
  package_size_name: string;
  barcode: string;
  width: string;
  length: string;
  height: string;
  q: string;
  weight: string;
  qty: string;
  unit_price: string;
};
export type ShipperROCodeOption = { ro_code_id: number; shipper_id: number; ro_code: string; ro_name: string };
export type UpdateReceiveForm = <K extends keyof ReceiveForm>(field: K, value: ReceiveForm[K]) => void;
export type UpdatePackageForm = <K extends keyof PackageRow>(field: K, value: PackageRow[K]) => void;
